composes:
  compose0:
    features: [mysql8, xwiki9mysql, tomcat8, openjdk9]
    services:
      mysql: {image: 'mysql:9'}
      web:
        depends_on: [mysql]
        image: xwiki9mysql:tomcat8-openjdk-9
  compose1:
    features: [mysql8, xwiki9mysql, tomcat8, openjdk9]
    services:
      mysql: {image: 'mysql:9'}
      web:
        depends_on: [mysql]
        image: xwiki9mysql:tomcat8-openjdk-9
  compose2:
    features: [mysql8, xwiki9mysql, tomcat8, openjdk9]
    services:
      mysql: {image: 'mysql:9'}
      web:
        depends_on: [mysql]
        image: xwiki9mysql:tomcat8-openjdk-9
watching: [web, postgres, mysql]
